chore: add .env file handling to backup scripts

diff --git a/s3-backup b/s3-backup
--- a/s3-backup
+++ b/s3-backup
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+# read .env file
+if [ -f .env ]; then
+    export $(grep -v '^#' .env | xargs)
+else
+    echo ".env file not found!"
+    exit 1
+fi
+
 echo "Test backup s3"
 echo "Test env:"
 
diff --git a/sql-backup b/sql-backup
--- a/sql-backup
+++ b/sql-backup
@@ -1,9 +1,15 @@
 #!/bin/bash
 
-
-
 SRC_DIR=/var/discourse/shared/standalone/backups/
-DST_DIR="
+DST_DIR=""
+
+# read .env file
+if [ -f .env ]; then
+    export $(grep -v '^#' .env | xargs)
+else
+    echo ".env file not found!"
+    exit 1
+fi
 
 echo "Test backup s3"
 echo "Test env:"
